# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate assert

Name:           rust-%{crate}
Version:        0.7.4
Release:        1%{?dist}
Summary:        Package provides assertions for testing

# Upstream license specification: Apache-2.0 and MIT
License:        ASL 2.0 and MIT
URL:            https://crates.io/crates/assert
Source:         %{crates_source}
# Initial patched metadata
Patch0:         assert-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description \
Package provides assertions for testing

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 14:35:27 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.7.4-1
- Initial package
