# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate ansi_term

Name:           rust-%{crate}
Version:        0.11.0
Release:        1%{?dist}
Summary:        Library for ANSI terminal colours and styles

License:        MIT
URL:            https://crates.io/crates/ansi_term
Source:         %{crates_source}
# Initial patched metadata
Patch0:         ansi_term-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description \
Library for ANSI terminal colours and styles (bold, underline).

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license  LICENCE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 15:48:40 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.11.0-1
- Initial package
