# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate atty

Name:           rust-%{crate}
Version:        0.2.11
Release:        1%{?dist}
Summary:        A simple interface for querying atty

License:        MIT
URL:            https://crates.io/crates/atty
Source:         %{crates_source}
# Initial patched metadata
Patch0:         atty-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(libc) >= 0.2.0 with crate(libc) < 0.3.0)

%global _description \
A simple interface for querying atty.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 15:49:22 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.2.11-1
- Initial package
