# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate lazy_static

Name:           rust-%{crate}
Version:        1.3.0
Release:        1%{?dist}
Summary:        A macro for declaring lazily evaluated statics in Rust

# Upstream license specification: MIT/Apache-2.0
License:        MIT and ASL 2.0
URL:            https://crates.io/crates/lazy_static
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description \
A macro for declaring lazily evaluated statics in Rust.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE-MIT LICENSE-APACHE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+spin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spin-devel %{_description}

This package contains library source intended for building other packages
which use "spin" feature of "%{crate}" crate.

%files       -n %{name}+spin-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+spin_no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spin_no_std-devel %{_description}

This package contains library source intended for building other packages
which use "spin_no_std" feature of "%{crate}" crate.

%files       -n %{name}+spin_no_std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 15:50:26 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 1.3.0-1
- Initial package
