# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate rawslice

Name:           rust-%{crate}
Version:        0.1.0
Release:        1%{?dist}
Summary:        Reimplementation of the slice iterators, with extra features. For example creation from raw pointers and start, end pointer accessors.

# Upstream license specification: MIT/Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/rawslice
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(rawpointer/default) >= 0.1.0 with crate(rawpointer/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(quickcheck) >= 0.4.0 with crate(quickcheck) < 0.5.0)
%endif

%global _description \
Reimplementation of the slice iterators, with extra features. For example\
creation from raw pointers and start, end pointer accessors.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 20:58:35 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.1.0-1
- Initial package
