# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate html2pango

Name:           rust-%{crate}
Version:        0.3.1
Release:        1%{?dist}
Summary:        Library to convert html to pango

# Upstream license specification: GPL-3.0
License:        GPLv3
URL:            https://crates.io/crates/html2pango
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(ammonia/default) >= 2.0.0 with crate(ammonia/default) < 3.0.0)
BuildRequires:  (crate(failure/default) >= 0.1.5 with crate(failure/default) < 0.2.0)
BuildRequires:  (crate(html5ever/default) >= 0.22.5 with crate(html5ever/default) < 0.23.0)
BuildRequires:  (crate(lazy_static/default) >= 1.3.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(linkify/default) >= 0.3.1 with crate(linkify/default) < 0.4.0)
BuildRequires:  (crate(maplit/default) >= 1.0.1 with crate(maplit/default) < 2.0.0)
BuildRequires:  (crate(regex/default) >= 1.1.2 with crate(regex/default) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(pretty_assertions/default) >= 0.6.1 with crate(pretty_assertions/default) < 0.7.0)
%endif

%global _description \
Library to convert html to pango.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 13:08:28 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.3.1-1
- Initial package
