# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate libhandy-sys

Name:           rust-%{crate}
Version:        0.3.0
Release:        1%{?dist}
Summary:        The sys part of the rust bindings for libhandy

License:        GPL-3.0-or-later
# FIXME: Upstream uses unknown SPDX tag GPL-3.0-or-later!
URL:            https://crates.io/crates/libhandy-sys
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(gdk-sys/default) >= 0.8.0 with crate(gdk-sys/default) < 0.9.0)
BuildRequires:  (crate(gdk/default) >= 0.10.0 with crate(gdk/default) < 0.11.0)
BuildRequires:  (crate(gio-sys/default) >= 0.8.0 with crate(gio-sys/default) < 0.9.0)
BuildRequires:  (crate(gio/default) >= 0.6.0 with crate(gio/default) < 0.7.0)
BuildRequires:  (crate(glib-sys/default) >= 0.8.0 with crate(glib-sys/default) < 0.9.0)
BuildRequires:  (crate(gobject-sys/default) >= 0.8.0 with crate(gobject-sys/default) < 0.9.0)
BuildRequires:  (crate(gtk-sys/default) >= 0.8.0 with crate(gtk-sys/default) < 0.9.0)
BuildRequires:  (crate(libc/default) >= 0.2.0 with crate(libc/default) < 0.3.0)
BuildRequires:  (crate(pkg-config/default) >= 0.3.7 with crate(pkg-config/default) < 0.4.0)
%if %{with check}
BuildRequires:  (crate(shell-words/default) >= 0.1.0 with crate(shell-words/default) < 0.2.0)
BuildRequires:  (crate(tempdir/default) >= 0.3.0 with crate(tempdir/default) < 0.4.0)
%endif

%global _description \
The sys part of the rust bindings for libhandy.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+dox-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dox-devel %{_description}

This package contains library source intended for building other packages
which use "dox" feature of "%{crate}" crate.

%files       -n %{name}+dox-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v0_0_6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v0_0_6-devel %{_description}

This package contains library source intended for building other packages
which use "v0_0_6" feature of "%{crate}" crate.

%files       -n %{name}+v0_0_6-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v0_0_7-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v0_0_7-devel %{_description}

This package contains library source intended for building other packages
which use "v0_0_7" feature of "%{crate}" crate.

%files       -n %{name}+v0_0_7-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v0_0_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v0_0_8-devel %{_description}

This package contains library source intended for building other packages
which use "v0_0_8" feature of "%{crate}" crate.

%files       -n %{name}+v0_0_8-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 13:13:29 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.3.0-1
- Initial package
