# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate letter-avatar

Name:           rust-%{crate}
Version:        1.0.2
Release:        1%{?dist}
Summary:        Generates user avatars using username initials

License:        GPL-3.0+
# FIXME: Upstream uses unknown SPDX tag GPL-3.0+!
URL:            https://crates.io/crates/letter-avatar
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(cairo-rs/default) >= 0.5.0 with crate(cairo-rs/default) < 0.6.0)
BuildRequires:  (crate(cairo-rs/png) >= 0.5.0 with crate(cairo-rs/png) < 0.6.0)
BuildRequires:  (crate(pango/default) >= 0.5.0 with crate(pango/default) < 0.6.0)
BuildRequires:  (crate(pangocairo/default) >= 0.6.0 with crate(pangocairo/default) < 0.7.0)
BuildRequires:  (crate(unicode-segmentation/default) >= 1.2.1 with crate(unicode-segmentation/default) < 2.0.0)

%global _description \
Generates user avatars using username initials

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 09:21:59 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 1.0.2-1
- Initial package
