# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate regex

Name:           rust-%{crate}
Version:        1.1.6
Release:        1%{?dist}
Summary:        An implementation of regular expressions for Rust

# Upstream license specification: MIT/Apache-2.0
License:        MIT and ASL 2.0
URL:            https://crates.io/crates/regex
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(aho-corasick/default) >= 0.7.3 with crate(aho-corasick/default) < 0.8.0)
BuildRequires:  (crate(memchr/default) >= 2.0.2 with crate(memchr/default) < 3.0.0)
BuildRequires:  (crate(regex-syntax/default) >= 0.6.6 with crate(regex-syntax/default) < 0.7.0)
BuildRequires:  (crate(thread_local/default) >= 0.3.6 with crate(thread_local/default) < 0.4.0)
BuildRequires:  (crate(utf8-ranges/default) >= 1.0.1 with crate(utf8-ranges/default) < 2.0.0)
%if %{with check}
BuildRequires:  (crate(lazy_static/default) >= 1.0.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(quickcheck) >= 0.7.0 with crate(quickcheck) < 0.8.0)
BuildRequires:  (crate(rand/default) >= 0.6.5 with crate(rand/default) < 0.7.0)
%endif

%global _description \
An implementation of regular expressions for Rust. This implementation uses\
finite automata and guarantees linear time matching on all inputs.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md PERFORMANCE.md CHANGELOG.md HACKING.md UNICODE.md
%license LICENSE-MIT LICENSE-APACHE
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pattern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pattern-devel %{_description}

This package contains library source intended for building other packages
which use "pattern" feature of "%{crate}" crate.

%files       -n %{name}+pattern-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+unstable-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-devel %{_description}

This package contains library source intended for building other packages
which use "unstable" feature of "%{crate}" crate.

%files       -n %{name}+unstable-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+use_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_std-devel %{_description}

This package contains library source intended for building other packages
which use "use_std" feature of "%{crate}" crate.

%files       -n %{name}+use_std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 17:08:23 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 1.1.6-1
- Initial package
