# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate fractal-matrix-api

Name:           rust-%{crate}
Version:        4.0.0
Release:        1%{?dist}
Summary:        Library to communicate with a Matrix.org server

# Upstream license specification: GPL-3.0
License:        GPLv3
URL:            https://crates.io/crates/fractal-matrix-api
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(cairo-rs/default) >= 0.5.0 with crate(cairo-rs/default) < 0.6.0)
BuildRequires:  (crate(cairo-rs/png) >= 0.5.0 with crate(cairo-rs/png) < 0.6.0)
BuildRequires:  (crate(chrono/default) >= 0.4.6 with crate(chrono/default) < 0.5.0)
BuildRequires:  (crate(chrono/serde) >= 0.4.6 with crate(chrono/serde) < 0.5.0)
BuildRequires:  (crate(glib/default) >= 0.6.1 with crate(glib/default) < 0.7.0)
BuildRequires:  (crate(log/default) >= 0.4.6 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(md5/default) >= 0.6.1 with crate(md5/default) < 0.7.0)
BuildRequires:  (crate(regex/default) >= 1.1.0 with crate(regex/default) < 2.0.0)
BuildRequires:  (crate(reqwest/default) >= 0.9.5 with crate(reqwest/default) < 0.10.0)
BuildRequires:  (crate(serde/default) >= 1.0.82 with crate(serde/default) < 2.0.0)
BuildRequires:  (crate(serde_derive/default) >= 1.0.82 with crate(serde_derive/default) < 2.0.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.33 with crate(serde_json/default) < 2.0.0)
BuildRequires:  (crate(time/default) >= 0.1.41 with crate(time/default) < 0.2.0)
BuildRequires:  (crate(tree_magic/default) >= 0.2.1 with crate(tree_magic/default) < 0.3.0)
BuildRequires:  (crate(url/default) >= 1.7.2 with crate(url/default) < 2.0.0)
BuildRequires:  (crate(urlencoding/default) >= 1.0.0 with crate(urlencoding/default) < 2.0.0)

%global _description \
Library to communicate with a Matrix.org server.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE.txt
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 16:21:51 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 4.0.0-1
- Initial package
