# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate twoway

Name:           rust-%{crate}
Version:        0.2.0
Release:        1%{?dist}
Summary:        Fast substring search for strings and byte strings

# Upstream license specification: MIT/Apache-2.0
License:        MIT and ASL 2.0
URL:            https://crates.io/crates/twoway
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(memchr) >= 2.0.0 with crate(memchr) < 3.0.0)
BuildRequires:  (crate(memchr/use_std) >= 2.0.0 with crate(memchr/use_std) < 3.0.0)
BuildRequires:  (crate(unchecked-index/default) >= 0.2.2 with crate(unchecked-index/default) < 0.3.0)
%if %{with check}
BuildRequires:  (crate(itertools/default) >= 0.7.0 with crate(itertools/default) < 0.8.0)
BuildRequires:  (crate(macro-attr/default) >= 0.2.0 with crate(macro-attr/default) < 0.3.0)
BuildRequires:  (crate(newtype_derive/default) >= 0.1.0 with crate(newtype_derive/default) < 0.2.0)
BuildRequires:  (crate(odds/default) >= 0.3.0 with crate(odds/default) < 0.4.0)
BuildRequires:  (crate(odds/std-string) >= 0.3.0 with crate(odds/std-string) < 0.4.0)
BuildRequires:  (crate(quickcheck) >= 0.7.0 with crate(quickcheck) < 0.8.0)
BuildRequires:  (crate(rand/default) >= 0.6.0 with crate(rand/default) < 0.7.0)
%endif

%global _description \
Fast substring search for strings and byte strings. Optional SSE4.2\
acceleration (if detected at runtime) using pcmpestri. Memchr is the only\
mandatory dependency. The two way algorithm is also used by rust's libstd\
itself, but here it is exposed both for byte strings, using memchr, and\
optionally using a SSE4.2 accelerated version.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+all-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+all-devel %{_description}

This package contains library source intended for building other packages
which use "all" feature of "%{crate}" crate.

%files       -n %{name}+all-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+benchmarks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+benchmarks-devel %{_description}

This package contains library source intended for building other packages
which use "benchmarks" feature of "%{crate}" crate.

%files       -n %{name}+benchmarks-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+galil-seiferas-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+galil-seiferas-devel %{_description}

This package contains library source intended for building other packages
which use "galil-seiferas" feature of "%{crate}" crate.

%files       -n %{name}+galil-seiferas-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+jetscii-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+jetscii-devel %{_description}

This package contains library source intended for building other packages
which use "jetscii" feature of "%{crate}" crate.

%files       -n %{name}+jetscii-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+pattern-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pattern-devel %{_description}

This package contains library source intended for building other packages
which use "pattern" feature of "%{crate}" crate.

%files       -n %{name}+pattern-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+use_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+use_std-devel %{_description}

This package contains library source intended for building other packages
which use "use_std" feature of "%{crate}" crate.

%files       -n %{name}+use_std-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 20:37:24 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.2.0-1
- Initial package
