# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate aesni

Name:           rust-%{crate}
Version:        0.6.0
Release:        1%{?dist}
Summary:        AES (Rijndael) block ciphers implementation using AES-NI

# Upstream license specification: MIT OR Apache-2.0
License:        MIT or ASL 2.0
URL:            https://crates.io/crates/aesni
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(block-cipher-trait/default) >= 0.6.0 with crate(block-cipher-trait/default) < 0.7.0)
BuildRequires:  (crate(opaque-debug/default) >= 0.2.0 with crate(opaque-debug/default) < 0.3.0)
BuildRequires:  (crate(stream-cipher/default) >= 0.3.0 with crate(stream-cipher/default) < 0.4.0)
%if %{with check}
BuildRequires:  (crate(block-cipher-trait/default) >= 0.6.0 with crate(block-cipher-trait/default) < 0.7.0)
BuildRequires:  (crate(block-cipher-trait/dev) >= 0.6.0 with crate(block-cipher-trait/dev) < 0.7.0)
BuildRequires:  (crate(stream-cipher/default) >= 0.3.0 with crate(stream-cipher/default) < 0.4.0)
BuildRequires:  (crate(stream-cipher/dev) >= 0.3.0 with crate(stream-cipher/dev) < 0.4.0)
%endif

%global _description \
AES (Rijndael) block ciphers implementation using AES-NI.

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+ctr-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ctr-devel %{_description}

This package contains library source intended for building other packages
which use "ctr" feature of "%{crate}" crate.

%files       -n %{name}+ctr-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+nocheck-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nocheck-devel %{_description}

This package contains library source intended for building other packages
which use "nocheck" feature of "%{crate}" crate.

%files       -n %{name}+nocheck-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+stream-cipher-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-cipher-devel %{_description}

This package contains library source intended for building other packages
which use "stream-cipher" feature of "%{crate}" crate.

%files       -n %{name}+stream-cipher-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 16:00:32 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.6.0-1
- Initial package
