# Generated by rust2rpm
%bcond_without check
%global debug_package %{nil}

%global crate gstreamer-sys

Name:           rust-%{crate}
Version:        0.7.0
Release:        1%{?dist}
Summary:        FFI bindings to libgstreamer-1.0

License:        MIT
URL:            https://crates.io/crates/gstreamer-sys
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(glib-sys/default) >= 0.8.0 with crate(glib-sys/default) < 0.9.0)
BuildRequires:  (crate(gobject-sys/default) >= 0.8.0 with crate(gobject-sys/default) < 0.9.0)
BuildRequires:  (crate(libc/default) >= 0.2.0 with crate(libc/default) < 0.3.0)
BuildRequires:  (crate(pkg-config/default) >= 0.3.7 with crate(pkg-config/default) < 0.4.0)
%if %{with check}
BuildRequires:  (crate(shell-words/default) >= 0.1.0 with crate(shell-words/default) < 0.2.0)
BuildRequires:  (crate(tempdir/default) >= 0.3.0 with crate(tempdir/default) < 0.4.0)
%endif

%global _description \
FFI bindings to libgstreamer-1.0

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+dox-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dox-devel %{_description}

This package contains library source intended for building other packages
which use "dox" feature of "%{crate}" crate.

%files       -n %{name}+dox-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_0_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_0_10-devel %{_description}

This package contains library source intended for building other packages
which use "v1_0_10" feature of "%{crate}" crate.

%files       -n %{name}+v1_0_10-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_10-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_10-devel %{_description}

This package contains library source intended for building other packages
which use "v1_10" feature of "%{crate}" crate.

%files       -n %{name}+v1_10-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_12-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_12-devel %{_description}

This package contains library source intended for building other packages
which use "v1_12" feature of "%{crate}" crate.

%files       -n %{name}+v1_12-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_14-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_14-devel %{_description}

This package contains library source intended for building other packages
which use "v1_14" feature of "%{crate}" crate.

%files       -n %{name}+v1_14-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_2-devel %{_description}

This package contains library source intended for building other packages
which use "v1_2" feature of "%{crate}" crate.

%files       -n %{name}+v1_2-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_2_3-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_2_3-devel %{_description}

This package contains library source intended for building other packages
which use "v1_2_3" feature of "%{crate}" crate.

%files       -n %{name}+v1_2_3-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_4-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_4-devel %{_description}

This package contains library source intended for building other packages
which use "v1_4" feature of "%{crate}" crate.

%files       -n %{name}+v1_4-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_6-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_6-devel %{_description}

This package contains library source intended for building other packages
which use "v1_6" feature of "%{crate}" crate.

%files       -n %{name}+v1_6-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+v1_8-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+v1_8-devel %{_description}

This package contains library source intended for building other packages
which use "v1_8" feature of "%{crate}" crate.

%files       -n %{name}+v1_8-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 16:41:40 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.7.0-1
- Initial package
