# Generated by rust2rpm
%bcond_without check

%global crate comrak

Name:           rust-%{crate}
Version:        0.6.0
Release:        1%{?dist}
Summary:        A 100% CommonMark-compatible GitHub Flavored Markdown parser and formatter

# Upstream license specification: BSD-2-Clause
License:        BSD
URL:            https://crates.io/crates/comrak
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(clap/default) >= 2.32.0 with crate(clap/default) < 3.0.0)
BuildRequires:  (crate(entities/default) >= 1.0.1 with crate(entities/default) < 2.0.0)
BuildRequires:  (crate(lazy_static/default) >= 1.0.1 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(pest/default) >= 2.0.0 with crate(pest/default) < 3.0.0)
BuildRequires:  (crate(pest_derive/default) >= 2.0.0 with crate(pest_derive/default) < 3.0.0)
BuildRequires:  (crate(regex/default) >= 1.0.1 with crate(regex/default) < 2.0.0)
BuildRequires:  (crate(twoway/default) >= 0.1.8 with crate(twoway/default) < 0.2.0)
BuildRequires:  (crate(typed-arena/default) >= 1.4.1 with crate(typed-arena/default) < 2.0.0)
BuildRequires:  (crate(unicode_categories/default) >= 0.1.1 with crate(unicode_categories/default) < 0.2.0)
%if %{with check}
BuildRequires:  (crate(timebomb/default) >= 0.1.2 with crate(timebomb/default) < 0.2.0)
%endif

%global _description \
A 100% CommonMark-compatible GitHub Flavored Markdown parser and formatter.

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%{_bindir}/comrak

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+benchmarks-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+benchmarks-devel %{_description}

This package contains library source intended for building other packages
which use "benchmarks" feature of "%{crate}" crate.

%files       -n %{name}+benchmarks-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages
which use "clap" feature of "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sat Apr 27 15:30:36 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.6.0-1
- Initial package
