# Generated by rust2rpm
%bcond_without check

%global crate tree_magic

Name:           rust-%{crate}
Version:        0.2.1
Release:        1%{?dist}
Summary:        Determines the MIME type of a file by traversing a filetype tree.

License:        MIT
URL:            https://crates.io/crates/tree_magic
Source:         %{crates_source}
# Initial patched metadata
Patch0:         tree_magic-fix-metadata.diff

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(fnv/default) >= 1.0.0 with crate(fnv/default) < 2.0.0)
BuildRequires:  (crate(lazy_static/default) >= 1.3.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(nom/default) >= 2.0.0 with crate(nom/default) < 3.0.0)
BuildRequires:  (crate(parking_lot/default) >= 0.4.0 with crate(parking_lot/default) < 0.5.0)
BuildRequires:  (crate(petgraph/default) >= 0.4.0 with crate(petgraph/default) < 0.5.0)

%global _description \
Determines the MIME type of a file by traversing a filetype tree.

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate} %{_description}

%files       -n %{crate}
%doc README.md
%{_bindir}/tmagic

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+clap-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+clap-devel %{_description}

This package contains library source intended for building other packages
which use "clap" feature of "%{crate}" crate.

%files       -n %{name}+clap-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+cli-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cli-devel %{_description}

This package contains library source intended for building other packages
which use "cli" feature of "%{crate}" crate.

%files       -n %{name}+cli-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+num_cpus-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+num_cpus-devel %{_description}

This package contains library source intended for building other packages
which use "num_cpus" feature of "%{crate}" crate.

%files       -n %{name}+num_cpus-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+scoped_threadpool-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+scoped_threadpool-devel %{_description}

This package contains library source intended for building other packages
which use "scoped_threadpool" feature of "%{crate}" crate.

%files       -n %{name}+scoped_threadpool-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+staticmime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+staticmime-devel %{_description}

This package contains library source intended for building other packages
which use "staticmime" feature of "%{crate}" crate.

%files       -n %{name}+staticmime-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+tabwriter-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tabwriter-devel %{_description}

This package contains library source intended for building other packages
which use "tabwriter" feature of "%{crate}" crate.

%files       -n %{name}+tabwriter-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+walkdir-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+walkdir-devel %{_description}

This package contains library source intended for building other packages
which use "walkdir" feature of "%{crate}" crate.

%files       -n %{name}+walkdir-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Sun Apr 28 15:57:41 +06 2019 Yuriy Sharov <dead_mozay@nom-it.ru> - 0.2.1-1
- Initial package
